language: python
python:
- '2.6'
- '2.7'
install:
- touch README.txt
- pip install .
- pip install -r requirements.txt
- pip install pep8
- pip install coveralls
script:
- make check
- make test
after_success:
- coveralls
notifications:
  slack:
    secure: fCkmPpcIOM5Q7YFlHKaXF4SCirVmCK+CusH2jGTL7wql1OsXyooucVoB2V7IUsBuqKjR1I3aShIAuTGMZjboY6MCl+8n85cYsRpIzMWY7i4r7KKVL2EEWoX+plK6SlrzexkiteVHDJW9nwSv0bMWAtVavCyp6yxqbVaDU06oavo=
